### ISSUE TITLE
Layered Standard to represent maps and curves

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-ls-struct#1]
@klausschuch had presented an initial draft at a previous meeting. Could you please provide more information?

**Comment by TorstenBlochwitz** [comment]
@klausschuch : The structural naming convention requires parsing of the names, which is not really a nice concept. More imporatnt: A generic record approach allows to add additional semantics to groups of variables, which in case of utilizing the naming convention must be given to each of the variable belonging to such a record.

**Comment by TorstenBlochwitz** [comment]
The biggest advantage of using a generic record approach compared to a special syntax only for look-up-tables is for importers. In this way, importers have to implement the treatment of such records only once. Tools which do not provide a high sophisticated GUI for look-up tables simply keep the parameters belonging to this group together, which is definitely of some help for the user. The same mechanism would work for records of parameters and other applications we don't know yet.

There are lots of different look-up table implementations outside. The definition of a generic look-up table thing might be a lot of work. No importer will ever support all kinds of look-up tables. That's why, from my point of view, utilizing a more general concept from the beginning might be useful.

**Comment by t-sommer** [comment]
A Simulink 2-d lookup table block exported with FMI Kit's grtfmi.tlc looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<fmiModelDescription
  fmiVersion="2.0"
  guid="{3f6f5fd6-ed86-452c-9658-ebc2a1d5453f}"
  modelName="tables"
  generationTool="Simulink 9.8 (R2022b) 13-May-2022 with FMI Kit 3.0 (grtfmi.tlc, FixedStepDiscrete, 0.2 s)"
  generationDateAndTime="2023-03-23T16:24:19"
  author="TSR2"
  version="1.2">

  <CoSimulation
    modelIdentifier="tables"
    canBeInstantiatedOnlyOncePerProcess="true"
    canHandleVariableCommunicationStepSize="true">
  </CoSimulation>

  <DefaultExperiment
    startTime="0.0"
    stopTime="10.0"
    stepSize="0.2"/>

  <ModelVariables>

    <!-- Parameters -->
    <ScalarVariable name="Parameters.uDLookupTable_tableData[0,0]" valueReference="1" causality="parameter" variability="tunable">
      <Real start="4.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_tableData[1,0]" valueReference="2" causality="parameter" variability="tunable">
      <Real start="16.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_tableData[2,0]" valueReference="3" causality="parameter" variability="tunable">
      <Real start="10.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_tableData[0,1]" valueReference="4" causality="parameter" variability="tunable">
      <Real start="5.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_tableData[1,1]" valueReference="5" causality="parameter" variability="tunable">
      <Real start="19.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_tableData[2,1]" valueReference="6" causality="parameter" variability="tunable">
      <Real start="18.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_tableData[0,2]" valueReference="7" causality="parameter" variability="tunable">
      <Real start="6.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_tableData[1,2]" valueReference="8" causality="parameter" variability="tunable">
      <Real start="20.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_tableData[2,2]" valueReference="9" causality="parameter" variability="tunable">
      <Real start="23.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_bp01Data[0]" valueReference="10" causality="parameter" variability="tunable">
      <Real start="1.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_bp01Data[1]" valueReference="11" causality="parameter" variability="tunable">
      <Real start="2.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_bp01Data[2]" valueReference="12" causality="parameter" variability="tunable">
      <Real start="3.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_bp02Data[0]" valueReference="13" causality="parameter" variability="tunable">
      <Real start="1.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_bp02Data[1]" valueReference="14" causality="parameter" variability="tunable">
      <Real start="2.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_bp02Data[2]" valueReference="15" causality="parameter" variability="tunable">
      <Real start="3.0"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_maxIndex[0]" valueReference="16" causality="parameter" variability="tunable">
      <Integer start="2"/>
    </ScalarVariable>
    <ScalarVariable name="Parameters.uDLookupTable_maxIndex[1]" valueReference="17" causality="parameter" variability="tunable">
      <Integer start="2"/>
    </ScalarVariable>

    <!-- Inputs -->
    <ScalarVariable name="In1" valueReference="18" causality="input">
      <Real start="0"/>
    </ScalarVariable>
    <ScalarVariable name="In2" valueReference="19" causality="input">
      <Real start="0"/>
    </ScalarVariable>

    <!-- Outputs -->
    <ScalarVariable name="Out1" valueReference="20" causality="output">
      <Real/>
    </ScalarVariable>

  </ModelVariables>

  <ModelStructure>
    <Outputs>
      <Unknown index="20"/>
    </Outputs>
    <InitialUnknowns>
      <Unknown index="20"/>
    </InitialUnknowns>
  </ModelStructure>

</fmiModelDescription>
```

**Comment by chrbertsch** [comment]
(FMI Design Webmeeting)

Klaus: the most important questions is, whether to have something special for maps and curves, or have something more general.
Andreas: The records are similar to terminals.
Antoine: We can have parameters in terminals already
Andreas: why not use terminals? We could backport them? We could define new terminal kinds.
Klaus: matching rules not make sense. We would re-use only a part. E.g. an Icon does not really make sense (e.g. where to put it)
Andreas: Matching would not have a  meaning.
Torsten B: Icons are optional. Terminals are not a good way to express look-up tables. 
The general idea of "record" came to late for the "terminals"
Torsten: The benefit is simplicity for importers. A look-up table is mainly a group of variables and parameters. Why not define a record similar to terminals.
Klaus: we already have the naming convention.
Andreas: the ideas are very similar, but the terminals are already out. 
With the records one could do many things (e.g. create a layered standard on top of layered standards)
Klaus: even the matching rules could make sense
Torsten B.:  parameter would have to be equal.
I would keep terminals. using them for look-up tables feels strange.

Poll: Should we 
1) define something specific for maps and curves, 
2) define records and specialize them for maps and curves, or 
3) use terminals and specialize them for maps and curves 
(multiple votes possible)
1) Klaus, Antoine, Christian , Masoud, Daniel, Oliver (6)
2) Andreas, Torsten B., Antoine, Christian, Jumayev, Jan, Oliver, Klaus (8)
3) -
abstain: -

Andreas: which option would hinder us most?
Torsten: If we choose 1), and want to define records, we would have to start again and would have 3 layered standards
Klaus: if we choose 2), we have to comment on the naming convention.

**Comment by chrbertsch** [comment]
> Discussion about further parameters of a lookup table like inter-/extrapolation types. This could either be just a `RelatedParameter` without any further meaning (as mentioned in a comment before) or the different types could be specified (or better reference a standard). The importing tool could then for example show the surface of the lookuptable.
> 
> @andreas-junghanns pointed out that more could be done with this info. For example the user might want to give values on a different grid than the FMU exports.

Klaus: this looks comlicated.
Andreas: this is not very important.
Christian/Klaus: some tools could agree on common additinal parameter names. (e.g Modelica tools for combitables).
Klaus: the records could have additional attributes.
Torsten B: We could give recommendations how enums/strings for certain inter/extrapolation could look like

**Comment by chrbertsch** [comment]
FMI-Design Meeting (Klaus, Irina, Christian, Torsten S.)
(old example from Klaus with annotations https://github.com/klausschuch/Reference-FMUs/blob/lookup_tables/LookupMaps/FMI3.xml)

With both approaches we can reach what we want for look-up tables. 
Which way to follow has to be decided in a larger group.

Main concerns for "Record" approach:
- *overlap w.r.t structured naming convention* (If we have both structured naming convention, and records: which one has preference?)
Options: 
1) if using Records: require NamingConventions=flat
2) Allow  NamingConventions=structured, allow only Records with kind=RegularMap
3) allow parallel usage of NamingConvention=structured and use of Records (can lead ambiguities; how to display this?)
Ask interested parties in Records: would they export all structural information via records? (Would they use dot-notation for variables also in the case of using Records? Or would they define a new hierarchy

- *few xsd checks possible, procedural checks needed*

Issues for both approaches:

- Uniqueness for names of RegularMaps: unique w.r.t. RegularMaps and ModelVariables (of the FMU)
 (consequence: have to follow structured naming convention, if VariableNamingConvention=structured)
 - Optional: displayName for for referenced Variabls (similar concept as for memberName of Terminals)
 -  Can we define several co-domains in A) one table or B) several tables? 
 B) Preferred. (grouping of several regular maps could also be reached with structured naming convention map.map2d_v1 in https://github.com/modelica/fmi-ls-struct/issues/1#issuecomment-1458377628)
 - Use names:  "RegularMap", "Domain", "Co-Domain", "RelatedVariable"
 - Add optional description (to RegularMap / Record)

**Comment by chrbertsch** [comment]
Discussion in the larger group at the FMI Design meeting: 

Why not use the terminals of the core standard instead of a new concept of "records" that does similar things?

**Comment by chrbertsch** [comment]
(Discussion: Klaus, Irina, Christian)

- We would prefer using Terminals instead of defining an almost identical concept Records
- Technically this seems feasible
-  Introductory text in https://fmi-standard.org/docs/3.0/#fmiTerminalsAndIcons talks about "semantic groups of variables to ease connecting compatible signals". "Signals" are not defined anyway and we could clarify this and/or make this non-normative.

A first draft could looks like: 
```
<fmiTerminalsAndIcons fmiVersion="3.0">
  <Terminals>
    <Terminal name="a.b.c.map"" terminalKind="org.fmi-standard.fmi-ls-struct.regularMap" matchingRule="plug">
      <TerminalMemberVariable variableName="a.b.c.map_x" memberName="x" variableKind="org.fmi-standard.fmi-ls-struct.domain" />
      <TerminalMemberVariable variableName="a.b.c.map_y" memberName="y" variableKind="org.fmi-standard.fmi-ls-struct.domain" />
      <TerminalMemberVariable variableName="x.y.map_z" memberName="z" variableKind="org.fmi-standard.fmi-ls-struct.codomain" />
      <TerminalMemberVariable variableName="InterpolMechanism" memberName="InterpolationOptions" variableKind="org.fmi-standard.fmi-ls-struct.interpolationOptions" />
    </Terminal>
  </Terminals>
</fmiTerminalsAndIcons>
```

tbd. What to define what "matching" means in this context, define also "None" for matching rule.

**Comment by pmai** [comment]
The draft PR for clarification of terminals in 3.0.1 is modelica/fmi-standard#1885, please add further needed clarifications and add feedback...

**Comment by chrbertsch** [comment]
Discussion Web-meeting

Torsten B.: Usage of Terminals for parameter records and maps and curves seems far-fetched. Maps and curves helps users to display them.
Pierre: What is the semantic difference?
Torsten B.: This is not generic
Pierre: We switch between solving specific solution for maps and curves and generic solution for records. What are our goals?
Torsten S: Terminals and Icons are a different view on variables. It would not be good to have different of such views.
Klaus: and we have the structured naming convention ...
Klaus: we have to define in which name space the names are unique.
Pierre: Which problems do we want to solve?

Problem description: 

- realize loop-up tables (maps, curves): this is quite clear, and solution approaches are available
- parameter grouping (see slide 8 of https://github.com/modelica/fmi-design/blob/master/Meetings/2022/2022-10-25_27-F2F-FMI-Design-Meeting/Material/2022_10_25_LayeredStandardsFMI_Ideas_ESI.pdf)

Pierre: Look-up tables have more specific semantic than grouping of parameters.
Torsten B.: Look-up tables are more specific and have more semantic
Pierre: The generic problem is solved by Terminals. Parameter Groups are related to connections (Parameter group equality). This fits also to SSP view on parameters.
Pierre: if we would use the Terminals Concept, we would have to check the standard text.
Klaus, Pierre: we have to fulfill what is written in  3.0
Irina: In a future FMI version we could replace Terminals conept with Records, we should not define a parallel construct to Terminals
Klaus: with a specific format we could have XSD checking
Pierre: With XML1.1 this would also be possible for records and Terminals

Poll: Should we 

1.     define something specific for maps and curves,
2.     define records and specialize them for maps and curves, or
3.     use terminals and specialize them for maps and curves
        (multiple votes possible)
        
        in brackets: can live with this proposal, is not my favourite
        
1: (Torsten B.) (Pierre) Klaus, (Irina), (Christian), (Matthias), (Kahramon)
2: Torsten B, (Klaus)
**3: Andreas, Christian, (Matthias), Patrick, Timo, (Klaus), Daniel, Irina, Pierre** 
Abstain: Torsten S.

Next steps: 
Create proposal for look-up tables and parameter groups with Terminals, and then decide.

Klaus: what has to be changed in 3.0.x?
Pierre: At least we could include warning ("This will be clarified in 3.0.2")
Klaus: e.g. "signals" is undefined.
Torsten: TerminalKind, Matching rules and Variables kinds can be used for specialization.

Pierre: I will start a PR to clarify Signals ... i.e. --> e.g.
Torsten: Sentencen on causality is important, as some users though on acausal connectors

Start with layered standard: 
Pierre: start with "prosa", create both XSD 1.0 and XSD 1.1
Klaus: add attribute values in XSD ? 
Pierre: have to check if additional 1.1 schema can be applied to existing schema ...
Pierre: we could also provide a new schema for everything, not so good.

Klaus: I will change our examples on this variant.
Christian:  I will start with a draft PR for the "prosa".
Klaus: We will start with the maps and curves, "records" later

Klaus: displayNames vs. MemberNames? There is no "any" in XSD?
Pierre: über Annotations?
Klaus: ... one can realize it differently.

Next meeting: in two weeks web meeting

**Comment by chrbertsch** [comment]
I think this issue can be closed, as IMHO the poins are all reflected in the current draft
