### ISSUE TITLE
optional outputs of lookup tables

### ISSUE THREAD

**Issue by klausschuch** [modelica/fmi-ls-struct#10]
should we have outputs defined or treat outputs just like any other related variable?
if we have outputs, how to represent them and what are the constraints?

**Comment by klausschuch** [comment]
Meeting 14.5.2024:
we want to have optional outputs as well
variableKind `org.fmi-standard.fmi-ls-struct.codomain_output`
since we only allow one input per domain, we only allow at most one output per codomain.
for nonscalars, the sizes of the outputs have to be equal to the sizes of the input variable, if input is given.

**Comment by chrbertsch** [comment]
org.fmi-standard.fmi-ls-struct.map.domainOutput included in the current draft spec https://modelica.github.io/fmi-ls-struct/main/#_definition_of_terminalkind_attribute_values
