### ISSUE TITLE
Should we allow several co-domains per lookup-table

### ISSUE THREAD

**Issue by klausschuch** [modelica/fmi-ls-struct#5]
we could allow several codomain variables in the same regular map.
Just consider the example extending the previous examples:
```xml
<Terminals>
    <Terminal name="map2d" terminalKind="org.fmi-standard.fmi-ls-struct.regularMap" matchingRule="plug">
      <TerminalMemberVariable variableName="x" memberName="x" variableKind="domain" />
      <TerminalMemberVariable variableName="map_x" memberName="map_x" variableKind="domain_input" />
      <TerminalMemberVariable variableName="y" memberName="y" variableKind="domain" />
      <TerminalMemberVariable variableName="map_y" memberName="map_y" variableKind="domain_input" />
      <TerminalMemberVariable variableName="v" memberName="values" variableKind="codomain" />
      <TerminalMemberVariable variableName="v2" memberName="values2" variableKind="codomain" />
    </Terminal>
    <Terminal name="map1d" terminalKind="org.fmi-standard.fmi-ls-struct.regularMap" matchingRule="plug">
      <TerminalMemberVariable variableName="d" memberName="d" variableKind="domain" />
      <TerminalMemberVariable variableName="operating_point" memberName="curve_x" variableKind="domain_input" />
      <TerminalMemberVariable variableName="cd" memberName="codomain" variableKind="codomain" />
      <TerminalMemberVariable variableName="cd2" memberName="secondcodomain" variableKind="codomain" />
    </Terminal>
  </Terminals>
```

**Comment by klausschuch** [comment]
Meeting 7.11.2023:
yes, we allow such maps

Since the operating point is bound to the domain, all codomains share the same operating point.
If an FMU wants to expose different operating points, just expose different maps reusing the domain variables but with different (or the same if you use the map within the model but different operating points) codomain variables.

Domain and the corresponding input should have compatible units (obviously) but we will not mention anything about this fact in the layered standard.

**Comment by chrbertsch** [comment]
Multiple co-domains are allowed in the current spec https://modelica.github.io/fmi-ls-struct/main/#_variablekind_attribute_values_of_terminal_member_variables
