### ISSUE TITLE
How to specify maps whose domain and codomain values are defined in one matrix?

### ISSUE THREAD

**Issue by TorstenBlochwitz** [modelica/fmi-ls-struct#7]
Until now we only allow vector variables to be referenced as domain and codomain variables which contain the data of a map.

In Modelica Standard Library and other applications, values for domain and codomain are defined in one matrix.

How can we express such maps in LS struct?

**Comment by klausschuch** [comment]
Meeting F2F-Munich:
we could define terminalkinds for each of the modelica combitables.
If an fmi variable v contain the whole matrix (with the domain and codomain sampling points and the data), we could just reference the same variable in the domain and codomain entries and based on the terminalKind the importer can do the slicing to extract eh domain and codomain values.

```xml
<fmiTerminalsAndIcons fmiVersion="3.0">
  <Terminals>
    <Terminal name="map2d" terminalKind="org.fmi-standard.fmi-ls-struct.map.combitable1d" matchingRule="org.fmi-standard.fmi-ls-struct.map">
      <TerminalMemberVariable variableName="v" memberName="x" variableKind="org.fmi-standard.fmi-ls-struct.domain" />
      <TerminalMemberVariable variableName="v" memberName="y" variableKind="org.fmi-standard.fmi-ls-struct.domain" />
<TerminalMemberVariable variableName="in_y" memberName="in_y" variableKind="org.fmi-standard.fmi-ls-struct.domainInput" />
      <TerminalMemberVariable variableName="v" memberName="v" variableKind="org.fmi-standard.fmi-ls-struct.codomain" />
    </Terminal>
  </Terminals>
</fmiTerminalsAndIcons>
```

**Comment by klausschuch** [comment]
We agreed on the structure for such combitables and the specification will be reworked in #18
