### ISSUE TITLE
Define matching rule rules

### ISSUE THREAD

**Issue by klausschuch** [modelica/fmi-ls-struct#8]
The matchingRule attribute of terminals is mandatory. Hence we have to define which matchingRules are applicable for lookup tables represented as terminals.

**Comment by klausschuch** [comment]
Meeting 7.11.2023:
Matching rules matter for tools that don't care about this ls. We shouldn't use predefined matching rules (plug, bus, sequence) because such tools might create connections that don't make sense for such terminals.
Hence, we define a new matching rule that allows special treatment (whatever that means).

suggested name:
org.fmi-standard.fmi-ls-struct.map
Which indicates that the variableKind of the member should be considered for the connection of the individual members of the terminal.

**Comment by klausschuch** [comment]
Web-Meeting 7.5.2024:
We have to define a matching rule `org.fmi-standard.fmi-ls-struct.map`.
The number of domains must be the same and the names(+type+size) of all domains (i.e., `variableKind=org.fmi-standard.fmi-ls-struct.domain`) must match. If all domains match, connect all these domains. Connect all co-domains (`variableKind=org.fmi-standard.fmi-ls-struct.codomain`) that match. Don't connect variables with `variableKind=org.fmi-standard.fmi-ls-struct.domain_input`.

**Comment by chrbertsch** [comment]
Already included in current version of spec https://modelica.github.io/fmi-ls-struct/main/#_definition_of_map_specific_matchingrule
