### ISSUE TITLE
Add "point cloud data"

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-ls-struct#9]

**Comment by klausschuch** [comment]
We should define a different terminalKind.
name suggestions:
- org.fmi-standard.fmi-ls-struct.irregularMap
- org.fmi-standard.fmi-ls-struct.pointCloud

We could reuse the variableKind attribute values ("domain", "codomain" and "domain_input").

`regularMap? defines that the length of i-th domain corresponds to the size i-th dimension of a co-domain array.

Whereas for an irregularMap/pointCloud, all domains and codomains must have the same length.

**Comment by klausschuch** [comment]
Meeting F2F-Munich:
name should be org.fmi-standard.fmi-ls-struct.map.irregular

**Comment by chrbertsch** [comment]
Already included in current state of spec https://modelica.github.io/fmi-ls-struct/main/#_maps_sampled_on_a_irregular_grid_point_cloud
